### PR TITLE
Slovak team on the main pageSlovak is coming to town!

### PR DESCRIPTION
**Pull request by zstanecic**

### CODE REVIEW

**Comment by Olga-Yakovleva** [comment]
@zstanecic, there was a bug in this pr, fixed now: it didn't indent the new item in config.yaml.

**Comment by zstanecic** [comment]
Thanks for that!

I thought that there was some automatic check for these types of errors.

**Comment by Olga-Yakovleva** [comment]
Not in this repository. It would be nice if somebody who knows about 
such things created an action to run a Hugo build to check pull requests 
here.

**Comment by zstanecic** [comment]
Let me see it. Maybe I can see how to create this.

**Pull request merged**
